// <auto-generated />
using DevicesAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DevicesAPI.Data;

#nullable disable

namespace DevicesAPI.Migrations
{
    [DbContext(typeof(DevicesDb))]
    partial class DevicesDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevicesAPI.Devices", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adress")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<double?>("kWh_energy_consumption")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            id = 1,
                            adress = "Entryway",
                            description = "Motion Sensor",
                            kWh_energy_consumption = 0.75
                        },
                        new
                        {
                            id = 2,
                            adress = "Bedroom",
                            description = "Smart Light Bulb",
                            kWh_energy_consumption = 5.1999998092651367
                        },
                        new
                        {
                            id = 3,
                            adress = "Front Door",
                            description = "Security Camera",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 4,
                            adress = "Kitchen",
                            description = "Smart Refrigerator",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 5,
                            adress = "Backyard",
                            description = "Weather Sensor",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 6,
                            adress = "Front Door",
                            description = "Smart Lock",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 7,
                            adress = "Living Room",
                            description = "Air Quality Monitor",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 8,
                            adress = "Bathroom",
                            description = "Water Leak Detector",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 9,
                            adress = "Entertainment Room",
                            description = "Smart TV",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 10,
                            adress = "Wearable",
                            description = "Fitness Tracker",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 11,
                            adress = "Kitchen",
                            description = "Smart Oven",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 12,
                            adress = "Bathroom",
                            description = "Smart Mirror",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 13,
                            adress = "Bathroom",
                            description = "Smart Scale",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 14,
                            adress = "Garden",
                            description = "Automated Plant Watering System",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 15,
                            adress = "Front Door",
                            description = "Smart Doorbell",
                            kWh_energy_consumption = 0.75
                        },
                        new
                        {
                            id = 16,
                            adress = "Garage",
                            description = "Garage Door Opener",
                            kWh_energy_consumption = 5.1999998092651367
                        },
                        new
                        {
                            id = 17,
                            adress = "Pet Collar",
                            description = "Pet Tracker",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 18,
                            adress = "Bedroom",
                            description = "Smart Ceiling Fan",
                            kWh_energy_consumption = 2.5
                        },
                        new
                        {
                            id = 19,
                            adress = "Kitchen",
                            description = "Smart Faucet",
                            kWh_energy_consumption = 2.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
